name: Build and Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linters
        run: yarn lint

      - name: Run formatters
        run: yarn format

      - name: Verify TypeScript types
        run: yarn typecheck

      - name: Build project
        run: yarn build

      - name: Run test coverage
        run: yarn test:coverage
