name: Release and Publish
on:
  push:
    branches:
      - master

jobs:
  release-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Verify linters and formatters
      run: npm run lint && npm run format

    - name: Verify TypeScript types
      run: npm run typecheck

    - name: Run test coverage
      run: npm run test:coverage

    - name: Build project
      run: npm run build

    # - name: Create release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ github.ref }}
    #     release_name: Release ${{ github.ref }}
    #     draft: false
    #     prerelease: false

    # - name: Publish to npm
    #   uses: js-actions/gpr-publish@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    #   with:
    #     package_folder: ./dist
    #     package_tag: latest
    #     registry_url: https://registry.npmjs.org/
    #     prerelease: false
