name: 'Dev - PR Close'
on:
  push:
      branches:
        - '*'
  pull_request:
    # branches:
    #   - master
    types:
      - closed
jobs:
  merge_pr:
    name: 'PR Merged'
    # if: github.event.pull_request.merged == true
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#         with:
#           token: ${{ GITHUB_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: Git config
        run: |
          git config --global user.email "${{ secrets.GH_ORG_EMAIL }}"
          git config --global user.name "${{ secrets.GH_ORG_NAME }}"
      - name: Get current branch name
        id: branch-name
        run: echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
      - name: Get PR labels
        id: pr-labels
        run: |
          echo "PR_LABELS=${{ github.event.pull_request.labels.*.name }}" >> $GITHUB_ENV
          echo "PR_LABELS: ${{ env.PR_LABELS }}"
      - name: Apply version bump (major)
        if: contains(env.PR_LABELS, 'major')
        run: |
          echo "Applying version bump (major)"
          npm version major
      - name: Apply version bump (minor)
        if: contains(env.PR_LABELS, 'minor')
        run: |
          echo "Applying version bump (minor)"
          npm version minor
      - name: Apply version bump (patch)
        if: contains(env.PR_LABELS, 'patch')
        run: |
          echo "Applying version bump (patch)"
          npm version patch
      - name: Git push version bump
        run: git push origin ${{ env.BRANCH_NAME }} --follow-tags --force
      - id: set-version
        name: Output version change
        run: npm pkg get version
