name: NPM Version Bump

on:
  pull_request:
    types:
      - closed
    branches:
      - 'master'

jobs:
  npm_version_bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR labels
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const isMerged = pr.merged === true;
            const hasLabels = pr.labels.length > 0;

            if (isMerged && hasLabels) {
              console.log('PR was merged and has labels');
              const supportedLabels = ['minor', 'patch', 'major']
              
              const labels = pr.labels.map((label) => label.name);
              const versionLabel = labels.find((label) => supportedLabels.includes(label));

              if (!!versionLabel) {
                console.log('PR has version label');
                const versionType = versionLabel === 'minor' ? 'minor' : versionLabel === 'patch' ? 'patch' : 'major';
                const cmd = `npm version ${versionType}`;
                console.log('Running command:', cmd);

                // Запускаємо команду npm version для зміни версії пакета
                const { execSync } = require('child_process');
                execSync(cmd, { stdio: 'inherit' });

                console.log('Package version bumped');
              } else {
                console.log('PR does not have version label. Skipping version update');
              }
            } else {
              console.log('PR was not merged or does not have labels. Skipping version update');
            }
